In [24]:
import numpy as np
#Завдання №1
my_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(my_vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#Завдання №2
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Завдання №3
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 4  7  5  5  7]
 [10  2  1  3  2]
 [ 2  4  4  7  6]
 [ 4  6  7  2  5]
 [ 3  1  2  8  8]]


In [20]:
#Завдання №4
random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.51700643 0.27572586 0.81668476 0.095658  ]
 [0.84496838 0.85206775 0.45418724 0.54306677]
 [0.54833675 0.88713632 0.8604266  0.98711921]
 [0.06259999 0.48202161 0.80222192 0.15479467]]


In [19]:
#Завдання №5
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("Масив 1:", array1)
print("Масив 2:", array2)


sum_result = array1 + array2
difference_result = array1 - array2
product_result = array1 * array2


print("Сума:", sum_result)
print("Різниця:", difference_result)
print("Добуток:", product_result)

Масив 1: [10  7  4  9  4]
Масив 2: [ 8  5  2  9 10]
Сума: [18 12  6 18 14]
Різниця: [ 2  2  2  0 -6]
Добуток: [80 35  8 81 40]


In [18]:
#Завдання №6
vector1 = np.random.random(7)
vector2 = np.random.random(7)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)


dot_product = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product)

Вектор 1: [0.19864593 0.86624238 0.78426338 0.32283869 0.36871464 0.84692996
 0.29363753]
Вектор 2: [0.05453579 0.1380731  0.18139393 0.99203444 0.69544365 0.50761247
 0.49396613]
Скалярний добуток: 1.424345260195771


In [17]:
#Завдання №7
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)


result_matrix = np.dot(matrix1, matrix2)


print("\nРезультат перемноження:")
print(result_matrix)








Матриця 1:
[[1 5]
 [3 2]]

Матриця 2:
[[ 4  2  6]
 [ 1  9 10]]

Результат перемноження:
[[ 9 47 56]
 [14 24 38]]


In [16]:
#Завдання №8
matrix = np.random.randint(1, 11, size=(3, 3))
print("Матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця є виродженою, обернена матриця не існує.")

Матриця:
[[7 1 9]
 [2 3 3]
 [4 3 7]]

Обернена матриця:
[[ 0.42857143  0.71428571 -0.85714286]
 [-0.07142857  0.46428571 -0.10714286]
 [-0.21428571 -0.60714286  0.67857143]]


In [15]:
#Завдання №9
matrix = np.random.rand(4, 4)
print("Матриця:")
print(matrix)


transposed_matrix = np.transpose(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця:
[[0.82383345 0.06488189 0.04866924 0.56881036]
 [0.76311023 0.72448983 0.34791574 0.33006334]
 [0.6230349  0.97254837 0.90416617 0.0084156 ]
 [0.61791357 0.06427207 0.09792003 0.56731865]]

Транспонована матриця:
[[0.82383345 0.76311023 0.6230349  0.61791357]
 [0.06488189 0.72448983 0.97254837 0.06427207]
 [0.04866924 0.34791574 0.90416617 0.09792003]
 [0.56881036 0.33006334 0.0084156  0.56731865]]


In [25]:
#Завдання №10
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)


result_vector = np.dot(matrix, vector)
print("\nРезультат перемноження:")
print(result_vector)

Матриця:
[[7 7 1 5]
 [4 2 2 8]
 [2 9 7 8]]

Вектор:
[ 9 10  4  5]

Результат перемноження:
[162 104 176]


In [26]:
#Завдання №11
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)


result_vector = np.dot(matrix, vector)
print("\nРезультат перемноження:")
print(result_vector)

Матриця:
[[0.8508694  0.93131973 0.48215032]
 [0.84995309 0.68467805 0.98124603]]

Вектор:
[0.18715912 0.53725846 0.96334749]

Результат перемноження:
[1.12408567 1.47220644]


In [27]:
#Завдання №12
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)


result_matrix = np.multiply(matrix1, matrix2)
print("\nРезультат поелементного множення:")
print(result_matrix)

Матриця 1:
[[5 7]
 [6 7]]

Матриця 2:
[[8 2]
 [6 9]]

Результат поелементного множення:
[[40 14]
 [36 63]]


In [28]:
#Завдання №13
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)


result_matrix = np.dot(matrix1, matrix2)


print("\nРезультат добутку матриць:")
print(result_matrix)

Матриця 1:
[[10  9]
 [ 6  3]]

Матриця 2:
[[2 9]
 [1 7]]

Результат добутку матриць:
[[ 29 153]
 [ 15  75]]


In [29]:
#Завдання №14
matrix = np.random.randint(1, 101, size=(5, 5))
print("Матриця:")
print(matrix)

sum_of_elements = np.sum(matrix)
print("\nСума елементів матриці:", sum_of_elements)

Матриця:
[[85 51 59 26 10]
 [51 74 31 36  6]
 [30 10 28  6 35]
 [39 88  8 86 30]
 [65 98 11 50 68]]

Сума елементів матриці: 1081


In [30]:
#Завдання №15
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

difference_matrix = np.subtract(matrix1, matrix2)
print("\nРізниця матриць:")
print(difference_matrix)

Матриця 1:
[[6 1 9 7]
 [7 7 4 6]
 [1 7 5 9]
 [7 8 7 3]]

Матриця 2:
[[ 7 10  1  5]
 [ 9  2  7  7]
 [ 3  3  8  8]
 [ 3 10  5  5]]

Різниця матриць:
[[-1 -9  8  2]
 [-2  5 -3 -1]
 [-2  4 -3  1]
 [ 4 -2  2 -2]]


In [31]:
#Завдання №16
matrix = np.random.rand(3, 3)
print("Матриця:")
print(matrix)

row_sums = np.sum(matrix, axis=1, keepdims=True)
print("\nВектор-стовпчик із сумою елементів кожного рядка:")
print(row_sums)

Матриця:
[[0.16321454 0.34611004 0.80293026]
 [0.41774426 0.10555914 0.6828009 ]
 [0.82307952 0.15475955 0.19787416]]

Вектор-стовпчик із сумою елементів кожного рядка:
[[1.31225484]
 [1.2061043 ]
 [1.17571323]]


In [32]:
#Завдання №17
original_matrix = np.random.randint(-10, 11, size=(3, 4))
print("Початкова матриця:")
print(original_matrix)

squared_matrix = np.square(original_matrix)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[  6   3  -8   3]
 [-10   9   0   0]
 [ -3   0   9  -4]]

Матриця з квадратами чисел:
[[ 36   9  64   9]
 [100  81   0   0]
 [  9   0  81  16]]


In [33]:
#Завдання №18
original_vector = np.random.randint(1, 51, size=4)
print("Початковий вектор:")
print(original_vector)

sqrt_vector = np.sqrt(original_vector)
print("\nВектор з квадратними коренями чисел:")
print(sqrt_vector)

Початковий вектор:
[15 14 18 42]

Вектор з квадратними коренями чисел:
[3.87298335 3.74165739 4.24264069 6.4807407 ]
